#!/usr/bin/env bash
if [ -f ".env" ]
then
  set -a
  . $PWD/.env
  set +a
fi

if [ "$1" != "" ]
then
  NODE_NAME="$1"
  shift 1
else
  echo "Unspecified node name!"
  exit 1
fi

if [ "$1" == "--" ]
then
  shift 1
fi

DEFAULT_OPTS=""
if [ "$KNIFE_NODE_DEFAULT_CONVERGE_OPTS" != "" ]
then
  DEFAULT_OPTS="$KNIFE_NODE_DEFAULT_CONVERGE_OPTS"
fi

bundle exec knife zero converge "$DEFAULT_OPTS" "$@" "name:$NODE_NAME"
